### ISSUE TITLE
policy-evaluator: evaluate a Rego policy converted to Wasm

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-evaluator#15]
* Turn https://github.com/flavio/burrego into a crate
* Allow the creation of a policy evaluator that can evaluate Rego code

Part of https://github.com/kubewarden/policy-evaluator/issues/14

**Comment by ereslibre** [comment]
https://github.com/wapc/wasmtime-provider/pull/10 is part of this work. The `burrego` crate was depending on `wasmtime` 0.28.0 and since we depend on that crate too but on version 0.24.0 -- and given [it links to the `system](https://github.com/bytecodealliance/wasmtime/blob/ebbe3997251add0278cc2de9c18dc43a1895f580/crates/fiber/Cargo.toml#L10-L14)`, only one crate version can exist in the dependency graph. Thus, as part of this work, [we had to bump the `wasmtime-provider` of the `wapc` project to 0.28.0 too](https://github.com/bytecodealliance/wasmtime/blob/ebbe3997251add0278cc2de9c18dc43a1895f580/crates/fiber/Cargo.toml#L10-L14), and so the dependency graph is solved for this project.
